//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kunden
    {
        public int ID { get; set; }
        public string Titel_Vor { get; set; }
        public string Vorname { get; set; }
        public string Nachname { get; set; }
        public System.DateTime Geburtstag { get; set; }
        public string C1_Wohnsitz { get; set; }
        public int C1_Postleitzahl { get; set; }
        public string C2_Wohnsitz { get; set; }
        public int C2_Postleitzahl { get; set; }
        public int Sozialversicherungsnummer { get; set; }
        public string Versicherungsanstalt { get; set; }
        public int Einkommen { get; set; }
        public string Titel_Nach { get; set; }
    }
}
